apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agentgateway-crds
  namespace: agentgateway-system
spec:
  interval: 10m
  chart:
    spec:
      chart: agentgateway-crds
      version: "v1.0.0"
      sourceRef:
        kind: HelmRepository
        name: agentgateway
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
