apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
  namespace: kagent
spec:
  interval: 10m
  dependsOn:
    - name: kagent-crds
  chart:
    spec:
      chart: kagent
      sourceRef:
        kind: HelmRepository
        name: kagent
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    agents:
      cilium-policy-agent:
        enabled: false
      cilium-manager-agent:
        enabled: false
      cilium-debug-agent:
        enabled: false
      istio-agent:
        enabled: false
      istio-policy-agent:
        enabled: false
      istio-manager-agent:
        enabled: false
    providers:
      default: gemini
      gemini:
        provider: Gemini
        model: "gemini-2.5-flash"
    kmcp:
      enabled: true
