apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agentgateway-system-ns.yaml
  - kagent-ns.yaml
  - agentgateway-crds-release.yaml
  - agentgateway-release.yaml
  - kagent-crds-release.yaml
  - kagent-release.yaml
