apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agentgateway
  namespace: agentgateway-system
spec:
  interval: 10m
  dependsOn:
    - name: agentgateway-crds
  chart:
    spec:
      chart: agentgateway
      version: "v1.0.0"
      sourceRef:
        kind: HelmRepository
        name: agentgateway
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
