apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent-crds
  namespace: kagent
spec:
  interval: 10m
  chart:
    spec:
      chart: kagent-crds
      sourceRef:
        kind: HelmRepository
        name: kagent
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
