apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  - gemini-secret.yaml
  - gemini-backend.yaml
  - gemini-route.yaml
  - configmap.yaml
  - model-config.yaml
  - agent.yaml
